### ISSUE TITLE
Upgrade Clojurescript, aleph and http-kit for JDK 9

### ISSUE THREAD

**Issue by tirkarthi** [Opetushallitus/ataru#512]
Hi,

It seems that the project uses versions of Clojurescript, aleph and http-kit that are incompatible with JDK 9. This is reported using Clojars metadata.

### Clojurescript : 

Latest Clojurescript release [1.10](https://clojurescript.org/news/2018-03-26-release) fixes JDK 9 compatibility issue caused by xml-bind. Relevant JIRA issue : https://dev.clojure.org/jira/browse/CLJS-2377 .

### http-kit : 

Relevant http-kit upstream issue : https://github.com/http-kit/http-kit/issues/356
Relevant release : https://github.com/http-kit/http-kit/releases/tag/2.3.0-beta2
Latest RC release : https://github.com/http-kit/http-kit/releases/tag/v2.3.0-RC1

### aleph : 

0.4.5-alpha1 (https://github.com/ztellman/aleph/commit/b4a49a878d73bb7db4178f7e62ddc9feb912f664).

Feel free to close this if it's irrelevant.

**Comment by elahti** [comment]
It has been a while, but these issues have been already resolved so closing this issue. Thanks for reporting!
